case "虚渊玄未参与以下哪部作品？": return "night Fate";
/*case "《摇曳百合》中京子喜爱的冰淇淋口味是什么": return "朗姆酒葡萄干";*/
case "灼眼的夏娜中女主角的刀名字叫": return "贽殿遮那";
case "命运石之门男主角的网名是": return "凤凰院凶真";
case "以下哪部游戏中没出现东风谷早苗？": return "东方神灵庙";
case "《CLANNAD》中的冈崎朋也的配音是谁？": return "中村悠一";
case "《火影忍者》中的第五代火影是谁？": return "千手纲手";
case "桂木桂马的协助者是谁？": return "艾露西  琉妮";
case "杀手47的后脑勺上有什么": return "条形码";
case "psycho pass里最美警花是谁?": return "宜野座伸元";
case "游戏《猎天使魔女》的女主角叫？": return "贝优妮塔";
case "雾雨魔理沙的口癖是？": return "DA☆ZE";
case "英雄联盟中人称草丛伦的是？": return "盖伦";
case "《英雄联盟》中赵信的所属势力名称是？": return "德玛西亚";
case "“月有阴晴圆缺”，用科学的观点看待这件事，原因是？": return "地球绕太阳转动，月球绕地球转动，两者转速不一样，出现偏角，使地球掩住了月球的一部分";
case "《我的朋友很少》中，井上麻里奈为哪个角色配音？": return "三日月夜空 ";
case "游戏《生化危机1》的第一女主角是谁？": return "吉尔·瓦伦蒂安";
case "回转企鹅罐中一共有多少个ED？出了多少个OST": return "10，8";
case "DOTA地图的作者是谁？": return "羊刀";
case " 元首发动技能“摔笔”时，需消耗一根什么笔": return "铅笔";
