var v = "题库题数：594 \n最后更新：2014.05.13";
k();
function b(q)
{
  switch(q)
  {
//128 | 4 + 57 | 4 + 269 | 0 + 26 | 0 + 4 | 0 + 20 | 0 + 20 | 0 + 62 > 594
//题库01（已确认） - 128道 - 【群主】？（1043201997）提供 - 2014.05.04
case "Bilibili采用邀请码注册，注册满几个月以上的用户才能购买邀请码？": return "三个月";
case "自古红蓝出什么？": return "CP";
case "官方逼死了谁？": return "同人";
case "下面哪位是个中二少女": return "小鸟游六花";
case "暴漫中“荆轲刺秦王”的下一句是": return "两条毛腿肩上扛";
case "团战可以输，____必须死？": return "提莫";
case "《命运石之门》中凤凰院凶真的配音是？": return "宫野真守";
case "以下哪部动漫不是京阿尼（京都动画公司）制作的？": return "FZ";
case "《海贼王》的作者是谁？": return "尾田荣一郎";
/*10*/case "《科学的超电磁炮》中，Lever.5被称为？": return "超能力者";
case "《魔法少女小圆》的导演是谁？": return "新房昭之";
case "奥特曼来自哪个星云？": return "m78";
case "奥特曼的家在哪里": return "M78";
case "《龙与虎》中的龙指的是谁？": return "高须龙儿";
case "十万个冷笑话是哪家漫画网连载的": return "有妖气";
case "地球距离月球之间的距离为？": return "384,400千米";
case "网络上11区指的是那个国家？": return "日本";
case "日语“我爱你”的空耳是什么？": return "阿姨洗铁路";
case "《某科学的超电磁炮》中，佐天同学经常对初春同学做的一件事情是什么？": return "掀裙";
/*20*/case "著名虚拟偶像初音未来的声源是谁？": return "藤田咲";
case "沙盒游戏“我的世界”的英文名是什么？": return "minecraft";
case "《Fate/ZERO》中Saber的Master是谁？": return "卫宫切嗣";
case "《魔法的禁书目录》中的特殊能力是什么？": return "魔法和超能力";
case "自称为“爱的战士”的人是谁？": return "虚渊玄";
case "请问FFF团的宗旨是什么？": return "烧死异性恋";
case "电磁炮四主角中谁的能力是空间移动？": return "白井黑子";
case "宅界的“东方”指的是什么": return "东方project";
case "桂木桂马自封的称号是？": return "攻略之神";
case "《魔法少女小圆》中巴麻美学姐是哪一话死的？": return "第三话";
/*30*/case "《 某科学的超电磁炮》中 最后之作 的检体番号是多少？": return "检体番号20001";
case "哪个不属于“钉宫四萌”？": return "神乐";
case "以下动漫少女哪个是金色双马尾？": return "A三千院凪";
case "三国杀online中，马超的台词是？": return "全军突击";
case "《千本樱》的原唱是谁？": return "初音未来";
case "《这样算是僵尸吗？》中优克莉伍德·海尔赛兹的能力是？": return "言灵";
case "“我已经看到结局了”这句经典台词是出自于哪部动画？": return "《只有神知道的世界》";
case "钉宫理惠的无路赛一般为多少个": return "3";
case "TO LOVE中大家喜闻乐见的小姨子是谁": return "梦梦";
case "《天降之物》里，伊卡洛斯最喜欢什么水果？": return "西瓜";
/*40*/case "《龙与虎》中逢坂大河和谁终成眷属": return "高须龙儿";
case "计算机编程中常见的if语句是？": return "判断语句";
case "《某科学的超电磁炮S》中的御坂美琴用什么放电磁炮？": return "用硬币";
case "被动漫爱好者称之为“梨神”的所属动漫作品是下列哪一项？": return "《To Loveる》";
case "动漫，漫画，游戏的简称是什么": return "ACG";
case "历代《口袋妖怪》的三只初始口袋妖怪的属性是？": return "草、水、火";
case "动漫《缘之空》的女主角叫什么名字？": return "春日野穹";
case "水的化学式怎么书写？": return "H₂O";
case "下列哪个动漫角色不是竹达彩奈配音的妹系角色？": return "住之江亚香-亲吻姐姐";
case "下列那种描述最接近“MAD”的含义？": return "二次创作影像";
/*50*/case "一种类似人生掌控者的，也指脱宅后大部分时间花在现实生活中的人": return "现充";
case "以下哪部作品不是京都制作的？": return "little busters";
case "陆逊一手牌无中，当他使用完之后（未被无懈）会得到几张手牌？": return "三张";
case "第一宇宙速度是？km/s": return "7.9";
case "凉宫春日是什么团的团长？": return "SOS团";
case "肥料掺了____，一袋能顶两袋撒": return "金坷垃";
case "哪个角色被叫做bilibili？": return "御坂美琴";
case "天才麻将少女中宫永咲擅长以什么方式胡牌": return "岭上开花";
case "宫永咲的绰号是什么？": return "大魔王";
case "《潜行吧！奈亚子》中克子的本体是什么？": return "克图格亚星人";
/*60*/case "《某科学的超电磁炮》的女主角御坂美琴在动漫界的俗称为": return "炮姐";
case "德布罗意波长公式是？": return "E=hv";
case "\"世界已完蛋\"出自哪部作品": return "奈亚子";
case "直到我膝盖中了一箭出自哪里": return "上古卷轴5";
case "《狼与香辛料》的作者是谁？": return "支仓冻砂";
case "《天才麻将少女》的女主角宫永咲在什么情况下麻将实力较强？": return "不穿袜子时";
case "KEY社三大“催泪弹”不包括": return "FATE/STAY NIGHT";
case "《命运石之门》中的椎名 真由理的配音是谁": return "花泽香菜";
case "fate stay night和fate zero中的吉尔伽美什别称什么？": return "金闪闪";
case "《某科学的超电磁炮》中“炮姐”是指以下哪人？": return "御坂美琴";
/*70*/case "被网友称为“世界第一吃货殿下”的是": return "洛天依";
case "枪兵的幸运等级": return "E";
case "以下哪个不是高级程序设计语言": return "汇编语言";
case "扶他出去!": return "YOOOOOO";
case "下列哪个不是Microsoft产品": return "Android";
case "X在叫，人坏掉，请问X是什么": return "蝉";
case "《天降小册子》L 不抱膝坐，推理能力会降低多少？": return "40%";
case "“我的XX可是突破天际的XX”中XX指的是什么": return "钻头";
case "请问洛天依的声源是谁？": return "山新";
case "未来日记中我妻由乃的声优是谁": return "村田知沙";
/*80*/case "最强的肥料是什么？": return "金坷垃";
case "下列人物中头上没有呆毛的是？": return "冈崎汐";
case "SAO是下列哪部动漫的缩写？": return "刀剑神域";
case "邪王真眼的拥有者": return "小鸟游六花";
case "老滚是哪个著名RPG游戏的昵称？（中文四字）": return "上古卷轴";
case "常言道，FFF團不燒什麼？": return "真愛";
case "B站会员初始收藏视频上限是多少？": return "40";
case "声优钉宫理惠配音的角色常常没有？": return "胸";
case "【夜神月】千本櫻 ——你认为此视频最有可能出现在哪里？": return "二次元鬼畜";
case "三国杀online中，董卓的台词是？": return "我是不是该减肥啦";
/*90*/case "和我签订契约，成为____吧": return "魔法少女";
case "以下不是niconico御三家的是": return "魔法少女小圆";
case "《日常》中名乃的真实身份是？": return "机器人";
case "马猴烧酒是什么东东？": return "魔法少女";
case "动漫中转学生一般不可能是？": return "普通学生";
case "对于新番动画，每年第一季度是？（2字）": return "冬季";
case "“給我一個支點，我可以撬動地球。”这句话是谁说的？": return "阿基米德";
case "轻音少女平泽唯的声优是？": return "丰崎爱生";
case "殴打小朋友系列的作者是谁？": return "狗HANK";
case "以下哪位动漫角色没有呆毛": return "不破爱花（绝园的暴风雨）";
/*100*/case "东方Project中简称为红白的是谁？": return "博丽灵梦";
case "吉田松阳的声优是": return "山寺宏一";
case "平乳是稀缺___": return "资源";
case "游戏《上古卷轴》里最经常中箭的地方是？": return "膝盖";
case "炮姐的真名叫做？": return "御坂美琴";
case "请问PSP上以下哪个键不不存在的？": return "C";
case "“打麻将真开心啊”出自下列哪部动漫？": return "咲-SAKI";
case "以下哪个不属于钉宫四萌？": return "神崎·H·亚里亚";
case "Vividred Operation的官方twitter名叫什么？": return "ビビッドレッド・オペレーション";
case "ACG界名词“京阿尼”指的是？": return "京都动画公司";
/*110*/case "下列哪国人没有参加金坷垃的争夺？": return "韩国人";
case "言叶之庭的导演是谁？": return "新海诚";
case "三国杀可以使用下列哪个技能自杀？": return "驱虎";
case "wow中被称为小芊芊的职业是": return "盗贼";
case "FFF团的出处是哪里呢？": return "笨蛋，测验，召唤兽";
case "一切都是谁的错？": return "时臣";
case "“荆轲刺秦王，两条毛腿肩上扛。”出自哪里？": return "暴走漫画";
case "“不学礼，无以立”。出于何处？": return "《论语》";
case "自古红蓝出什么": return "CP";
case "声优御三家不包括？": return "植田佳奈";
/*120*/case "TV动画《狼与香辛料》当中，男主角罗伦斯的配音是谁？": return "福山润";
case "刀剑神域的男主角是谁？": return "桐谷和人";
case "白井黑子什麼時候出生？": return "7月14日";
case "凉宫春日又称": return "团长";
case "“真相只有一个！”这句经典台词出自于哪部动画？ ": return "《名侦探柯南》";
case "三爷有几块腹肌？": return "8块";
case "《天降之物》中笨蛋是谁？": return "阿斯特蕾亚";
case "《FATE》中saber不愿意被士狼看到自己洗澡的原因是": return "纯害羞";
case "椎名真白的声优是？": return "茅野爱衣";
//题库02（已确认） - 4道 - 优子（352275201）提供 - 2014.05.05
case "动漫《刀剑神域》中亚丝娜的角色歌歌名为？": return "My Independent Destiny";
case "当PCl5 = PCl3 +Cl2的化学平衡常数Kc=1.8M时，在0.5L的容器中加入0.15molPCl5,求平衡后Cl2的浓度": return "0.26M";
case "《怪物猎人3G》中两只奇面族的名字分别叫什么？": return "茶茶，卡扬巴";
case "以下角色与其他角色性别不同的是？": return "木下秀吉";
//题库02（未确认） - 57道 - 优子（352275201）提供 - 2014.05.05
case "「蓝蓝路教主」中「教主」的形象原型出自哪一个连锁饮食业公司？": return "麦当劳";
case "《叛逆的鲁鲁修》中的鲁鲁修的配音是谁?": return "福山润";
case "名曲《最珍贵的宝物》（“一番の宝物”）出自哪个作品？": return "Angel Beats";
case "洛天依中文音源是由哪位声优提供？": return "山新";
case "FSN和FZ中吉尔伽美什的真正宝具是什么": return "王之财宝";
case "《圣斗士》中黄金圣衣一共有多少件？": return "12件";
case "游戏《星际争霸》《暗黑破坏神》等是哪个公司制作的？": return "Blizzard";
case "代号47是哪个游戏中的主角？": return "杀手";
case "APH中意呆的声优是谁": return "浪川大辅";
case "C语言中，如果ar是个数组，那么表达式ar[i]与什么等价？": return "*(ar+i)";
case "銀魂中\"昙天\"是什麼意思?": return "阴天";
case "《扑杀天使》中小骷髅的咒语是什么？": return "哔哔噜哔噜哔噜哔哔噜哔";
case "阿良良木历帮谁刷牙了？": return "火怜 ";
case "化物语的监督是谁？": return "新房昭之";
case "零之使魔中露易丝在托里斯汀所打工的酒馆前身叫什么": return "鳗鱼之睡床";
case "以下声优中被称为组长的是": return "杉田智和";
case "成年人及年长儿正常心胸比例不大于": return "0.5";
case "海贼王的作者是？": return "尾田荣一郎 ";
case "我国大陆家庭电路的电压统一使用为多少伏？": return "220";
case "著名武打男星比利海灵顿最常从事的体育运动是？": return "摔跤";
case "北极熊的毛是什么颜色？": return "透明";
case "美树沙耶加所爱的人是谁？": return "上条恭介";
case "160兵长的声优是？": return "娘娘 ";
case "《玉子超市》中牧野神奈的配音是谁？": return "长妻树里 ";
case "《潜行吧！奈亚子》中邪神奈亚拉托提普的天敌是？": return "克图格亚";
case "下列人物不属于黑白后宫的是": return "博丽灵梦";
case "罪恶王冠男主的名字": return "樱满集 ";
case "浦科特m5p固态硬盘采用的是什么主控芯片": return "Marvell 88SS9187-BLD2";
case "著名游戏制作人板垣伴信的绰号是什么？": return "硫酸脸";
case "《AIR》的女主角的名字？": return "神尾观铃";
case "凉宫的小说中无尽的八月一共重复了多少遍？": return "15532 ";
case "《Fate/zero》的剧本是谁写的？": return "虚渊玄";
case "被称为神谷娘娘的是哪位声优？": return "神谷浩史";
case "未来日记中我妻由乃的声优是谁": return "村田知沙";
case "新生物性状产生的根本原因在于？": return "基因重组";
case "绫崎飒一开始欠下的债务是": return "¥150000000 ";
case "《神薙》中花泽香菜的角色是？": return "忏悔酱 ";
case "12年底被广泛玩坏的转手指op是出自哪部动画。": return "中二病也要谈恋爱";
case "以下哪部作品的监督不是新房昭之？": return "夏目友人帐";
case "动漫《火影忍者》中，宇智波佐助所拥有的瞳术的名字是？": return "写轮眼";
case "下列哪种角色不属于暴雪游戏《暗黑破坏神3》？": return "程序员 ";
case "以下KEY社的游戏的剧本创作，哪个麻枝准没有参与？": return "REWRITE";
case "罪恶王冠的拔剑神曲是谁写的": return "泽野弘之";
case "《寒蝉鸣泣之时》中的古手梨花的口头禅是什么？": return "咪啪 ";
case "以下轩辕剑的哪一部作品主角是女性？": return "苍之涛";
case "金坷垃好处都有啥（下一句话": return "谁说对了就给他";
case "NICONICO表·御三家不包括": return "创价学会";
case "物质波是由谁提出来的": return "德布罗意";
case "《天空之城》的主题曲是什么？": return "伴随着你";
case "无头骑士的声优是谁？": return "泽城美雪 ";
case "请问下列哪首V家歌曲以“就不给人翻唱”而闻名？": return "初音ミクの消失";
case "以下电视台总部位于香港的是？": return "凤凰卫视";
case "烧死异性恋的FFF团源自哪部日本动漫。": return "笨蛋测验召唤师";
case "《魔法禁书目录》中的上条当麻是如何让特异能力无效化的？": return "使用右手";
case "阿拉垃圾君是谁的外号": return "阿良良木历 ";
case "比利是教什么科目的": return "哲学";
case "只有神知道的世界中的偶像通常指的是谁？": return "中川花音";
//题库03（已确认） - 4道 - 优子（352275201）提供 - 2014.04.30
case "TV动画《进撃の巨人》第6集中 “少女の奔跑”巨人是谁干掉的？": return"三笠·阿克曼";
case "阿卡林的原名是...": return"赤座燈里";
case "幽灵行军不是谁的固有结界": return"梵·斐姆";
case "以下那個不是釘宮四萌?": return"神崎·H·亞里亞";
//题库03（未确认） - 269道 - 优子（352275201）提供 - 2014.04.30
case "灼眼的夏娜中女主角的刀名字叫": return"贽殿遮那";
case "《摇曳百合》中京子喜爱的冰淇淋口味是什么": return"朗姆酒葡萄干";
case "命运石之门男主角的网名是": return"凤凰院凶真";
case "以下哪部游戏中没出现东风谷早苗": return"东方神灵庙";
case "《CLANNAD》中的冈崎朋也的配音是谁？": return"中村悠一";
case "《火影忍者》中的第五代火影是谁？": return"千手纲手";
case "桂木桂马的协助者是谁？": return"艾露西 琉妮";
case "杀手47的后脑勺上有什么": return"条形码";
case "psycho pass里最美警花是谁?": return"宜野座伸元";
case "《数码兽大冒险》中第八位被选召的孩子是？": return"八神光/八神嘉儿";
case "雾雨魔理沙的口癖是？": return"DA☆ZE";
case "切丝papa的生日在几月几日？": return"11.11";
case "为动画《魔法少女小圆》中佐仓杏子一角配音的声优是？": return"野中蓝";
case "“月有阴晴圆缺”,用科学的观点看待这件事,原因是？": return"地球绕太阳转动,月球绕地球转动,两者转速不一样,出现偏角,使地球掩住了月球的一部分";
case "《我的朋友很少》中,井上麻里奈为哪个角色配音？": return"三日月夜空";
case "游戏《生化危机1》的第一女主角是谁？": return"吉尔·瓦伦蒂安";
case "回转企鹅罐中一共有多少个ED？出了多少个OST": return"10，8";
case "身为纯爷们,绝对从不回头看什么": return"爆炸";
case "以下哪一位不是《最终幻想：零式》的CV": return"钉宫理惠";
case "《大航海时代2》阿兰的特长是什么？": return"会计";
case "钢之炼金术师FA中角色张梅身边总跟着一只什么动物": return"小熊猫";
case "Fate stay night中,士郎击杀Berserker所投影的武器叫？": return"Caliburn石中剑";
case "初音未来的音源提供者是哪个声优？": return"藤田咲";
case "著名电子游戏《上古卷轴》是由哪家公司开发的？": return" Bethesda";
case "石蕗惠汰,羽濑川小鹰,须贺京太郎,大路饼藏四人的共同点[不]包括": return"都是男孩子";
case "在Mugen中,最高的人物等级是？": return"论外";
case "圣斗士星矢的看家技能是？": return"天马流星拳";
case "魔兽世界里的联盟英雄吉安娜是什么职业": return"法师";
case "谁被称为日本动画界的黑泽明？": return"宫崎骏";
case "“世界已完蛋”来自于哪部作品OP的空耳？": return"潜行吧奈亚子";
case "炮姐的最爱是？": return"呱太";
case "美少女战士的作者是哪位漫画家的夫人？": return"富坚义博";
case "陈坤在微博向大家推荐了哪部动画得到群众热烈反应？": return"《Fate/Zero》";
case "在FATE STAY NIGHT 中阿尔托莉雅的职介是什么": return"Saber";
case "正面上我啊是哪个人物的名台词": return"御坂美琴";
case "为《星际牛仔》《攻壳机动队》《Macross F》等动画配乐的著名音乐制作人是": return"菅野洋子";
case "⑨指的是东方project中的那个人物？": return"琪露诺";
case "《天降之物》第一集中从天而降的天使名字是？": return"伊卡洛斯";
case "路过草从最担心的是哪句话？": return"德玛西亚";
case "《海贼王》中与路飞同行的一位厨师是": return"香吉士";
case "自古枪兵的幸运值是多少": return"e";
case "德玛西亚之力此人物出自哪个游戏？": return"《英雄联盟》";
case "虽然我可爱又迷人,但我会招来__。": return"死亡";
case "key社以下哪一部作品不是由京都动画改编？": return"Little Busters!";
case "动漫11区指哪里？": return"日本";
case "《CLANNAD》中,藤林杏的摩托车是什么颜色的？": return"白色";
case "《穷神》中红叶是什么罩杯？": return"AA罩杯";
case "《兽的演奏者艾琳》中的里岚是雄性还是雌性？": return"雌性";
case "东方幻想乡中妖怪之山上守矢神社中的风祝叫什么名字？": return"东风谷早苗";
case "《電腦線圈》中的沙奇(Search Mutton),是甚麼？": return"病毒驱除程式";
case "雾雨魔理沙在东方神灵庙（TH13）中的称号是？": return"普通的魔法使";
case "薛定谔的猫是薛定谔的一个著名实验,其不涉及的问题是 ": return"势垒穿透";
case "《海贼王》中现任海军元帅的是谁？": return"赤犬";
case "暴走漫画的男主角一般都叫什么？": return"王尼玛";
case "小鸟游六花的中二属性是什么？": return"邪王真眼";
case "傅里叶级数是傅里叶在研究哪种物理现象时提出的？": return"热传导";
case "阿姆斯特朗回旋加速喷气式阿姆斯特朗炮“的名字出自哪部动漫": return"《银魂》";
case "火影忍者中4代火影和主角鸣人是什么关系？": return"父子";
case "dota是哪个游戏的地图?": return"魔兽世界";
case "在《死亡笔记》中,是谁杀死了夜神月？": return"硫克";
case "机战里常说的“吉姆王”是出自哪一部作品": return"传说巨神";
case "以下哪一个游戏在早期2D时代的第一部作品不是俯视角？": return"银河战士";
case "无头骑士异闻录中罪歌到11卷出现了几个母体？": return"2个";
case "《魔笛MAGI》中梶裕貴配音的角色是谁？": return"阿里巴巴";
case "兵库北的天气怎么样？": return"雨 19℃ 60%/40% 24岁";
case "“海尔,这是阿包特·泰姆”这句台词出自哪款游戏？": return"星际争霸2";
case "被成为“一生万物、万物归一者”的是": return" Yog-Sothoth";
case "《旋风管家》中的女主角三千院凪的身高是？(直接输入阿拉伯数字） ": return"138";
case "银河英雄传说中男主角杨威利是如何死亡的": return"被地球教刺客刺杀";
case "动漫（雪之少女）泽渡真琴,的口头禅是什么 ": return"啊呜";
case "《魔法少女小圆》的编剧（脚本）是谁？": return"虚渊玄";
case "下列哪个角色不是关智一配音的？": return"基拉·大和";
case "是谁提出“感应电流的磁场总是要阻碍引起感应电流的磁通量的变化“?": return"楞次";
case "动漫《火影忍者》中,宇智波佐助所拥有的瞳术的名字是？": return"写轮眼";
case "《轻音少女》动画中,活动室里养的动物是？": return"乌龟";
case "灼眼的夏娜中夏娜所带的项链中红世之徒的名字是": return"亚拉斯托尔";
case "国产动画片《魁拔》中,魁拔的重生时间是": return"333年";
case "以下哪一款RPG（角色扮演游戏）属于WRPG（欧美角色扮演游戏）？": return"博德之门";
case "C语言中，如果ar是个数组，那么表达式ar[i]与什么等价？": return"*(ar+i)";
case "c语言中换行符是？": return"\\n";
case "某万事屋老板的名字是？": return"坂田银时";
case "以下那部动画的配乐不是梶浦由纪？": return"fate stay night";
case "《某科学超电磁炮》中 御坂美琴的硬币大约能打多少米？": return"50米";
case "以下哪个动漫人物被作为我朝四代隐形战机的爱称？": return"秋山澪";
case "EVA新剧场版中真希波玛丽眼镜镜框的颜色是": return"红色";
case "世界第一公主殿下是谁": return"初音未来";
case "哔哩哔哩是什么类型的网站?": return"弹幕视频";
case "2012年日萌萌王是谁": return"园城寺怜";
case "《穿越火线》由国内哪家公司代理运营？": return"腾讯";
case "下列各项不属于电脑操作系统的是": return"S60";
case "国际标准化组织ISO制定的OSI模型中,路由器工作在哪一层？": return"网络层";
case "下列谁没有担任《机动战士高达V》的机设": return"安彦良和";
case "mugen人物实力一共有几个级别": return"7个";
case "由Nintendo公司发售的8位游戏机的名称缩写是什么？": return"FC";
case "（）,你一定不懂吧。括号里的名字是？": return"心叶";
case "团长的名字是": return"凉宫春日";
case "空之境界中与阴性人格式相反的阳性人格是?": return"织";
case "东方project中不死组指的是那对CP": return"妹红X辉夜";
case "《蔷薇少女》中翠星石的瞳色是？": return"左绿右红";
case "当PCl5 = PCl3 +Cl2的化学平衡常数Kc=1.8M时,在0.5L的容器中加入0.15molPCl5,求平衡后Cl2的浓度": return"0.26M";
case "《to love》中的梨斗的妹妹的配音是谁？": return"花泽香菜";
case "以下哪位角色脸上没有刀疤？": return"阿鲁卡多@HELLSING";
case "“我的这把刀可是涂满了毒药的毒刃”出自于哪部作品": return"勇士闯魔城";
case "下列动画作品中,那一部是由京都动画公司制作的。": return"幸运星";
case "高达鲁姆会战中吉翁一方出动了多少艘姆赛级巡洋舰？": return"69";
case "《加速世界》男主角是谁？": return"有田春雪";
case "《今天开始做魔王》中,涉谷有利第一次是怎么穿越的？": return"被女厕的抽水马桶冲到异界";
case "在缩写“ACG”中字母“G”代表什么？": return"Game";
case "在动漫《叛逆的鲁路修》中,C.C.的头发的颜色是？": return"绿色";
case "凡能从石台上拔出此剑者,即为英格兰的天命之王。出自哪部动漫？": return"命运之夜";
case "3dmax中旋转视图按哪个键": return"alt+鼠标中键";
case "以下哪个不是鬼畜全明星成员？": return"金凯瑞";
case "游戏《帝国时代2》中,中国的特色兵种是？": return"诸葛弩手";
case "“钉宫病”是指有关哪位声优的病症？": return"钉宫理惠";
case "晓美焰的声优是？": return"斋藤千和";
case "下列哪个人物与《kiss×sis》中「住之江理香」的配音相同？": return"蕾蒂西亚";
case "请问被称为名作之壁的是什么动漫？": return"Infinite Stratos";
case "我国4个直辖市中哪个面积最大？": return"重庆";
case "《clannad》中藤林杏所养的宠物小野猪的名字是什么？": return"牡丹";
case "葛平的职业是？（说正经的）": return"配音演员";
case "日语的元音的罗马音是？": return"aiueo";
case "农业不发达,必须要有什么？": return"金克拉";
case "《十二国记》的作者是谁": return"小野不由美";
case "《青之驱魔师》是作者是那位？": return"加藤和惠";
case "以下哪一部作品的剧本不是虚渊玄？": return"尘骸魔京";
case "游戏MONSTER HUNTER 3G 中共有几种武器？": return"12";
case "夏目友人帐中的猫咪老师（斑）被动漫爱好者称呼为？": return"娘口三三";
case "元首曾经去过中国的哪个省份？": return"河北省";
case "钉宫四萌哪个出现的最早 ": return"夏娜";
case "动漫《FATE ZERO》中,Rider的名字是？": return"亚历山大·伊斯坎达尔";
case "官方逼死了谁？": return"同人";
case "北极熊的毛是什么颜色？": return"透明";
case "《死神》现任二番队队长大人的名字是？": return"碎蜂";
case "“不要叫我大王,要叫我_______！” 空缺处填？": return"女王大人";
case "拼音“s”的发音是？": return"唇齿清擦音";
case "零之使魔中露易丝在托里斯汀所打工的酒馆前身叫什么": return"鳗鱼之睡床";
case "《龙与虎》中的逢坂大河声优是谁？": return"钉宫理惠";
case "下列各项不属于电脑操作系统的是": return"S60";
case "Operation Skuld出自哪部动画？": return"Chaos;Head";
case "FFF团作为一种自发组织的民间团体主要活动形式是？": return"烧死情侣";
case "哪部是key社所谓的秋？": return"One";
case "以下哪个不是国产游戏。": return"空之轨迹";
case "虚渊玄被称为？（四个中文汉字）": return"爱的战士";
case "一部动漫名称,《XXXX的忧郁》,XXXX应为？": return"凉宫春日";
case "动画《回转企鹅罐》的监督是谁？": return"几原邦彦";
case "《Angel Beast》的女主角是谁？": return"立华奏";
case "以下谁拥有Geass的能力？": return"鲁鲁修";
case "新日暮中的黑暗势力统领是谁？": return"VAN样";
case "XX我成为正义的伙伴了吗？": return"切嗣";
case "400大妈是指": return"东映蜘蛛人";
case "海猫鸣泣之时的武具是叫什么名字？": return"谢斯塔姐妹兵";
case "key君是谁？": return"杉崎健";
case "以下哪个地区代表未出现在金克拉广告中？": return"俄罗斯";
case "以下哪个人不属于ACG界四大人渣？": return"结城梨斗";
case "某部机甲动漫中出现的经典台词是？": return"我爸爸都没打过我！";
case "阿良良木历有几个妹妹？": return"2个";
case "金坷垃三人组里的非洲人叫什么名字。": return"东仙队长";
case "以下哪部作品没有得过这本轻小说真厉害排行榜的第一？": return"龙与虎";
case "逢坂大河是哪部作品的主角": return"龙与虎";
case "洛天依的声源是": return"山新";
case "《机动战士高达00》中刹那.f.清英的配音是谁？": return"宫野真守";
case "《Love Live!》中的小泉花阳最喜欢的食物是。": return"白米饭";
case "NTSC制式的视频帧率是": return"30fps";
case "博丽灵梦所在的神社是什么？": return"博丽神社";
case "日本剑圣宫本武藏自创的武术是什么？": return"二天一流";
case "“今天的风儿好喧嚣啊”的出处。": return"男子高中生的日常";
case "声优喜多村英梨被中国网友戏称为？": return"酋长";
case "下面哪个角色不是浪川大辅配的？": return"怪盗基德";
case "《虫之歌》中的狮子堂戌子绰号是？": return"小狗";
case "回转企鹅罐中一共有多少个ED？出了多少个OST？": return"10,8";
case "以下不是光色三原色的是？": return"绿色";
case "高达的英文缩写是。": return"GUNDAM";
case "蒙奇·D·路飞出自哪个作品。": return"海贼王";
case "“给我一个支点,我可以撬动地球”这句话是谁说的？": return"阿基米德";
case "《中二病也要谈恋爱》中小鸟游六花的姐姐叫什么名字？": return"小鸟游十花";
case "《英雄联盟》中盖伦是哪个势力的。": return"德玛西亚";
case "《化物语》中战场原黑仪的配音是谁？": return"斋藤千和";
case "春秋战国时期,哪家学说的主张是“兼爱”“非攻”？": return"墨家";
case "《未来日记》中女主叫什么名字？": return"我妻由乃";
case "路飞的爷爷是？": return"海军";
case "“拔刀,拔刀,拔刀”出自哪部漫画？": return"K";
case "下列动画作品中,那一部是由京都动画公司制作的。": return"幸运星";
case "高达鲁姆会战中吉翁一方出动了多少艘姆赛级巡洋舰？": return"69";
case "在缩写“ACG”中字母“G”代表什么？": return"Game";
case "在动漫《叛逆的鲁路修》中,C.C.的头发的颜色是？": return"绿色";
case "凡能从石台上拔出此剑者,即为英格兰的天命之王。出自哪部动漫？": return"命运之夜";
case "日语的元音的罗马音是？": return"aiueo";
case "《十二国记》的作者是谁": return"小野不由美";
case "《青之驱魔师》是作者是那位？": return"加藤和惠";
case "以下哪一部作品的剧本不是虚渊玄？": return"尘骸魔京";
case "游戏MONSTER HUNTER 3G 中共有几种武器？": return"12";
case "拼音“s”的发音是？": return"唇齿清擦音";
case "动画《回转企鹅罐》的监督是谁？": return"几原邦彦";
case "《Angel Beast》的女主角是谁？": return"立华奏";
case "以下谁拥有Geass的能力？": return"鲁鲁修";
case "英雄联盟中国服三大永久免费英雄之一是？": return"流浪法师";
case "声优界中的大辅家族不包括以下哪个姓": return"铃木";
case "《无头骑士异闻录》中,黄巾贼的首领被称呼为？": return"将军";
case "以下哪一个动画原作者是男性？": return"黑塔利亚";
case "空条Q太郎在JOJO里出场了多少部？": return"3部";
case "2ch上某gal讨论板块“叶键版”分别指的是那两个游戏厂商": return"Moon Laef&Key ";
case "Fate Zero第二季中的OP作者是谁": return"梶浦由记";
case "以下哪个词是来自日语,意为不引人注意的小知识": return"豆知识";
case "魂中吉原的百华自卫队首领是？": return"月咏";
case "最终幻想零式中,machina最多可以展开强力攻击多少次": return"10";
case "下列哪个不是最早的“讲卫生除四害”之中的“四害”": return"蟑螂";
case "“夏亚你算计我”这句话是哪位人物的名言": return"卡尔玛 扎比";
case "亚洲颜艺三巨头不包括？": return"葛炮";
case "\"只要是活着的东西,即使是神也杀给你看\"是下面哪个人的名言？": return"两仪式";
case "以下哪一位CV不属于声优御三家": return"花泽香菜";
case "中国的第一艘航空母舰叫什么名字": return"辽宁号";
case "以下哪一位不属于type moon？": return"小山广和";
case "光线是波动,也是（ )。": return"粒子";
case "《to love》中的梨斗的妹妹的配音是谁？": return"花泽香菜";
case "“我的这把刀可是涂满了毒药的毒刃”出自于哪部作品": return"勇士闯魔城";
case "高达鲁姆会战中吉翁一方出动了多少艘姆赛级巡洋舰？": return"69";
case "《加速世界》男主角是谁？": return"有田春雪";
case "路飞的爷爷是？": return"海军";
case "“拔刀,拔刀,拔刀”出自哪部漫画？": return"K";
case "《凉宫春日的忧郁》中谁是“外星人”？": return"长门有希";
case "刺客信条中的袖箭不切手指是被谁改进的？": return"艾吉奥";
case "最喜欢从人群中钻出来的关头是谁？": return"吴克";
case "以下哪个游戏不是saga planets的作品": return"さくら、咲きました";
case "战略大作战这部电影当中，主角们做了啥？": return"开着谢尔曼抢银行";
case "开着谢尔曼抢银行": return"花泽香菜";
case "《哆啦A梦》中多啦A梦是从什么时代来的？": return"22世纪";
case "国产动画《魁拔》中，主角的名字是？": return"蛮吉";
case "游戏公司“南梦宫”有一个数字缩写，是什么？": return"765";
case "坦克世界中唯一一辆满仇恨值的黄金色坦克是什么？": return"59式";
case "问更新姬的发式": return"绿色双马尾";
case "网络上11区指的是那个国家？": return"日本";
case "刺客信条中的袖箭不切手指是被谁改进的？": return"康纳";
case "《命运石之门》中凤凰院凶真的配音是？": return"宫野真守";
case "真女神轉生3 狂熱版’中，但丁和人修羅初次見面的地點是？": return"銀座";
case "谁不懂人心了？": return"亚瑟王";
case "黑猫警长每集打四枪出现四个字是?": return"请看下集";
case "在鬼武者3最终关左马介吸收了信长的爱刀所融合出的最强之剑的正确名称是": return"鬼斩左文字";
case "人妻声优門脇舞以的马甲是？": return"杏子御津";
case "与洛天依有关的代码是？": return"66CCFF";
case "《口袋妖怪》历作游戏中，能够让PM的等级提高一级的道具是？": return"等级提升";
case "冻土的旅人中《白色荒野》一章改编自____的小说": return"杰克伦敦";
case "生化危机系列中，僵尸的始作俑者是？": return"T病毒";
case "绑在魂魄妖梦的楼观剑上的花叫什么名字": return"秋樱";
case "《圣斗士星矢》冥王篇中谁是被冥王哈迪斯选中肉体的圣斗士？": return"瞬";
case "以下哪个系列的发行商不是Ubisoft（育碧）": return"孤岛危机系列";
case "《伊克西翁传说DT》玛丽安戴尔的声优是？": return"福山润";
case "《中二病也要谈恋爱》当中丹生谷森夏从“中二病”毕业以后转而相信了什么": return"黑暗圣典";
case "《冰菓》中奉太郎的人生信条是？": return"节能主义";
case "《妖精的尾巴》中，妖精的尾巴公会的第二代灭龙魔导士是": return"拉克萨斯";
case "这个世界上不存在奇迹，有的只是必然与偶然，以及谁做了什么。此话出自什么动漫？": return" 悠久之翼（EF系列）";
case "“王师全面占优”出自下列哪个游戏？": return"EVE";
case "幻想乡里操纵境界的妖怪是？": return"八云紫";
case "地球距离月球之间的距离为？": return"384,400千米";
case "nds平台第一款游戏王是哪一年出的": return"2007";
case "miku左臂的数字是多少？": return"01";
case "&lt;犬夜叉&gt;中，戈薇的配音是谁？": return"雪野五月";
case "以下哪位人物是因为视力不好才戴眼镜的": return"黑桐干也";
case "赤座灯里最缺少的是什么？": return"存在感";
case "网游《坦克世界》中，S-51的完全体炮的口径是多少？": return"203";
case "UC系高达作品中象征着量产机的胜利的是哪部作品？": return"机动战士高达第08MS小队";
case "《物语系列》中谁的头发会飞速长长": return"阿良良木月火";
case "天元突破的男主角是谁？": return"西蒙";
case "命运石之门冈部伦太郎经常自称是谁？（名字）": return"凤凰院凶真";
case "以下哪个不是音频处理软件": return"Premiere";
case "《魔法少女小圆》中学姐死的时候失去了身体的哪一部分？": return"头";
case "《未来日记》中，“雪辉日记”的持有者是谁？": return"我妻由乃";
case "以下哪首是洛天依的歌": return"千年食谱颂";
case "动画《刀剑神域》中桐人他女儿结衣在ALO里系统识别种族是？": return"导航妖精";
case "俺はGandom（我就是高达）这句话是谁说的？": return"刹那·F·清英";
//题库04（已确认） - 0道 - Baby（79680406）提供 - 2014.05.09
//题库04（未确认） - 26道 - Baby（79680406）提供 - 2014.05.09
case "动画《魔笛》中小野大辅配音的角色叫什么？": return "辛巴德";
case "琴浦小姐的超能力是？": return "听得见别人的想法!";
case "《天降之物》中藤田咲配音的是谁？": return "樱井 智子";
case " “绅士”一词与下列那个词同义？": return "变态";
case "哪位不是平成三大歌姬?": return "安室奈美惠";
case "桐人是出自哪部动漫？": return "刀剑神域";
case "动画《中二病也要谈恋爱！》中，小鸟游六花的姐姐叫什么名字": return "小鸟游十花";
case "“拔刀、拔刀、拔刀”出自哪部动漫？": return "K";
case "一般来讲“俺妹”指的是哪部动画": return "我的妹妹不可能那么可爱";
case "《好想告诉你》中风早翔太的配音是谁": return "浪川大辅";
case "梶裕贵是《K》中的哪个人物的CV": return "十束多多良";
case "《银魂》的作者是谁？": return "空知英秋";
case "【银魂】中以下哪个人物不是【万事屋】的成员？": return "土方十四郎";
case "滑头鬼之孙二代的名字是？": return "奴良鲤伴";
case "下列哪个不是PSP的按键？": return "☆";
case "《灼眼的夏娜》中的夏娜的配音是谁?": return "钉宫理惠";
case "御坂美琴一般用什么发射电磁炮？": return "硬币";
case "《PSYCHO-PASS》中花泽香菜配音的妹子叫？": return "常守朱";
case "电视剧《巾帼枭雄之义海豪情》中，叫梁非凡去“吔屎啦”的人物是？": return "刘醒";
case "下列哪一项不是犬夜叉中铁碎牙的招式?": return "苍龙破";
case "下面哪个不是小野大辅役？": return "冈崎朋也";
case "《冰菓》中千反田爱瑠的声优是谁？": return "佐藤聪美";
case "执导动画电影《秒速5CM》的日本导演是？": return "新海诚";
case "TARI TARI中冲田纱羽的配音是谁": return "早见沙织";
case "《无头骑士异闻录》里的静雄的配音是谁？": return "小野大辅";
case "《JoJo的奇妙冒险》的作者是谁？": return "荒木飞吕彦";
//题库05（已确认） - 0道 - sxy648896648@qq.com提供 - 2014.05.10
//题库05（未确认） - 4道 - sxy648896648@qq.com提供 - 2014.05.10
case "下列属于酸的是？": return "H2SO4";
case "五岳，是中国五大名山的总称，以下那个选项不属于五岳？": return "峨眉";
case "CaC⒉ 的俗名什么？": return "电石";
case "C7H16有几种同分异构体": return "9";
//题库06（已确认） - 0道 - Feuler loup（410205366）提供 - 2014.05.10
//题库06（未确认） - 20道 - Feuler loup（410205366）提供 - 2014.05.10
case "《地狱少女》中的仙太郎的配音是谁？": return "丰永利行";
case "两仪式有几个人格": return "2";
case "以下哪首歌是Fate/Zero的OP": return "to the beginning";
case "以下那种波不是电磁波？": return "超声波";
case "街机上的《拳皇97》是由哪一个公司制作？": return "SNK";
case "国际通用的标准音的频率是？": return "440Hz";
case "初音岛上的万年萝莉是谁": return "芳乃樱";
case "刀剑神域中，桐人的妹妹名字叫？": return "桐谷直叶";
case "得了什么病也要谈恋爱？": return "中二病";
case "《未来日记》中的女主叫什么名字？": return "我妻由乃";
case "《我的青春恋爱物语果然有问题》女主角的名字是什么？": return "雪之下雪乃";
case "恶作剧之吻男主角名字是（）": return "入江直树";
case "游戏生化危机5的男主角叫什么": return "克里恩雷德菲尔德";
case "柯南的声优是？": return "高山南";
case " S/L大法在游戏中的意思是？": return "利用存档读档的手法";
case "未聞花名的ed【secret base】是翻唱誰的歌？": return "zone";
case "我国4个直辖市中哪个面积最大？": return "重庆";
case "常言道，FFF團不燒什麼？": return "真愛";
case "天上掉下本小册子是什么动漫？": return "死亡笔记";
case "我妻由乃 最常使用的武器是？": return "柴刀";
//题库07（已确认） - 0道 - SongTaste（342566877）提供 - 2014.05.10
//题库07（未确认） - 20道 - SongTaste（342566877）提供 - 2014.05.10
case "《圣斗士星矢》是哪一位漫画家的作品?": return "车田正美";
case "被称为死神小学生的是": return "柯南 ";
case "以下不是由盛大代理的网游": return "坦克世界 ";
case "元首到过下列哪个省": return "河北省";
case "《银魂》中真选组副长是": return "土方十四郎";
case "巡音Luka的声源是？": return "浅川悠";
case "一部动漫名称：《XXXX的忧郁》，XXXX应为？": return "凉宫春日";
case "以下那个县和花泽香菜的外号有关？": return "兵库";
case "《真三国无双》由哪家游戏公司开发？": return "KOEI";
case "日本被称为11区源自于什么动画": return "叛逆的鲁鲁修";
case "神奇宝贝里喷火龙的属性是？": return "火系和飞行系";
case "动漫《日在校园》中 伊藤诚被谁干掉的？": return "西园寺世界";
case "洛克人的第一部作品一开始可以选择几关？": return "6";
case "如果有人从草丛里蹦出来,那么他最有可能对你说?": return "德玛西亚";
case "一般来说，传言中的圆桌骑士由几人组成？": return "12人 ";
case "大陆的《魔兽世界》最早是由哪个游戏运营商代理的？": return "第九城市";
case "以下哪项是游戏《侠盗猎车手:罪恶都市》中不能使用的道具？": return "自行车";
case "\"既不回头，何必不忘”出自哪部游戏？": return "仙剑奇侠传";
case "凉宫春日是（）的团长": return "SOS团";
case "下列声优是90后的是": return "悠木碧";
//题库08（已确认） - 0道 - je（1298674946）提供 - 2014.05.12
//题库08（未确认） - 62道 - je（1298674946）提供 - 2014.05.12
case "天鹰战士是哪指部动画？": return "EVA";
case "口袋妖怪游戏中在完全随机的情况下，野外遇到闪光精灵的概率是？": return "1/8192";
case "最终幻想VIII中登场的女主角为：": return "莉诺雅";
case "微软最新家用机的名字是": return "xbox720";
case "<<月姬>>中公主的全名是？": return "爱尔奎特 布伦史塔德";
case "日语“欧尼酱”是什么意思？": return "哥哥";
case "以下哪个声优不是游戏《starry sky》的声优": return "森川智之";
case "《银魂》中万事屋的牌匾上写着什么": return "糖分";
case "《刀剑神域》中的亚丝娜的配音演员是谁": return "户松遥";
case "在动画《军火女王》中，代表我国在非洲利益的是？": return "大星海公司";
case "AIDS的全称是什么?": return "获得性免疫缺陷综合征";
case "宏观经济学中的AS指的是什么？": return "Aggregate Supply";
case "《东方妖妖梦》Phantasm面BOSS叫什么名字？": return "八云紫";
case "欢乐颂是贝多芬第几交响曲中的": return "第九交响曲";
case "以下哪个不是宫野真守配音的": return "龙之峰帝人";
case "minecraft中的creeper（苦力怕）最害怕什么生物？": return "猫";
case "以下哪一位不属于type moon？": return "虚渊玄";
case "《某科学的超电磁炮》里被称作\"炮姐\"的角色全名叫什么?": return "御坂美琴";
case "国产RPG单机游戏古剑奇谭一代的副标题是什么？": return "琴心剑魄今何在";
case "<花牌>和<恋连>告诉我们，名字叫（）的都是苦逼": return "太一";
case "“今天的风儿好喧嚣啊”为了帮朋友解围，这时你会说：": return "隔壁超市薯片半价了，快去买";
case "机战OG2第15话中将哪位四天王最后击破会有特殊奖励？": return "梅基保斯";
case "‘真女神轉生3 狂熱版’中，但丁和人修羅初次見面的地點是？": return "銀座";
case "以下哪位人物没有与QB签订契约成为魔法少女？": return "杨玉环";
case "“孤这一生，无怨无悔，只是，有少许遗憾啊..”是谁的台词？": return "龙溟";
case "篮球员麦迪先生的同事奥登大帝，曾经在媒体面前看过什么漫画书？": return "灌篮高手";
case "《魔兽世界》是哪个游戏公司出品的？": return "动视暴雪";
case "下面哪个不是11区声优“御三家”之一？": return "花泽香菜";
case "以下哪种力不属于性质力？": return "压力";
case "秒速五厘米中男女主角未能交换信件便分离时的BGM是": return "届かない気持ち";
case "_____的科学技术世界第一。": return "德意志";
case " 以下谁一心想做海贼王？": return "路飞";
case "美国圣地亚哥国际农资集团的真实注册地在？": return "河南郑州";
case "中二病也要谈恋爱中，六花一直想要寻找的是": return "不可视境界线";
case "伊卡牧师妹指的是谁？": return "乌贼娘";
case "心理测量者中日本采用什么系统鉴定罪犯？": return "先知系统";
case "《科学超电磁炮》中的电击使（Electro Master）是谁的能力？": return "御坂美琴";
case "日本麻将中，荣和30符4番，得点多少": return "7900";
case "《DOTA2》（刀塔）中地图右上方势力的名字是？": return "夜魇";
case "以下哪款耳机采用了特斯拉技术": return "拜亚T1";
case "《phycho pass》中常守朱的声优是": return "花泽香菜";
case "《科学超电磁炮》中白井黑子所属第几风纪委员支部？": return "风纪委员活动第177支部";
case "《科学超电磁炮》是哪部作品的外传？": return "《魔法禁书目录》";
case "自古（）出CP": return "红蓝";
case "火影忍者里和再不斩一起的叫什么名字？": return "白";
case "天文学上，红移是指": return "天体离我们远去";
case "强袭魔女第一季OP中屏幕下方出现的胖次是什么样式的": return "蓝白条纹";
case "传说中人称兵库北小姐的女性声优是": return "花泽香菜";
case "下列不属于基本粒子的是": return "光子";
case "我大KONAMI社的万年秘籍是？": return "↑↑↓↓←→←→BA";
case "《魔法禁书目录》中茵蒂克丝的配音是谁？": return "井口裕香";
case "以下不是由盛大代理的网游": return "坦克世界";
case "新日暮里中的黑暗势力统领是谁": return "VAN样";
case "《全职猎人》的蚂蚁篇中的“NGL”的代指什么？": return "国家名称缩写";
case "宫野真守给以下哪些人物配过音？": return "夜神月、须王环、纪田正臣";
case "《最终幻想零式》中的哪个角色和《最终幻想7核心危机》中的扎克斯声优相同？": return "Jack";
case "《龙与虎》中逢坂大河的配音是谁？": return "钉宫理惠";
case "金克拉最后给了谁？": return "美国鬼子";
case "被称之为达尔文的斗犬的是历史上哪一位人物？": return "托马斯•赫胥黎";
case "黑化御三家中角色诞生时间最早的是？": return "龙宫礼奈";
case "以下突出环保主题的宫崎骏动画是？": return "《风之谷》";
case "魔笛magi的作者是谁？": return "大高忍";
    default: return "hyErrNotFound";
  };
};
